### PR TITLE
fix: Add basic responsiveness (fixes #4)

### LINKED ISSUE #4: Add responsiveness to the home page
### Basic

- Find the folder `App.css` .

- Locate the class for which the css is to be added/changed .

- Edit the css and/or add css for different media sizes .

### Expected changes
```
@media only screen and (max-width: 768px) { 
   css data for this media size .
}
```

### PR DESCRIPTION
**Pull request by JoshSald**
Added some basic responsiveness. Far from ideal, but it's a start!

### CODE REVIEW

File: frontend_application/src/App.js [hunk 1]
```diff
@@ -1,69 +1,72 @@
...
+                <div className="description">{hero.description}</div>
+                <div className="powers_arrays">
+                  {hero.power.map((powers) => (
+                    <div
+                      className="power"
+                      style={{
+                        color: hero.text_color,
+                        backgroundColor: hero.widget_color,
+                      }}
+                    >
```
Comment (Aatmaj-Zephyr) [inline frontend_application/src/App.js:56]: code unclear

**Review by Aatmaj-Zephyr — COMMENTED** [review]
changes into code made
